"use client";
export const products = [
  {
    id: 1,
    image: "./trending1.jpg",
    name: "Square Textured Striped",
    price: "$19.99",
    actual_price: "$120",
    star: 5,
    variant: ["red", "yellow"],
    discount: "-20%",
  },
  {
    id: 2,
    image: "./trending2.jpg",
    name: "Rounded Neck T-Shirt",
    price: "$24.99",
    actual_price: "$720",
    star: 4.5,
    variant: ["blue", "green", "black"],
    discount: "-50%",
  },
  {
    id: 3,
    image: "./trending3.jpg",
    name: "Slim Fit Jeans",
    price: "$29.99",
    star: 4,
    discount: "-20%",
  },
  {
    id: 4,
    image: "./trending4.jpg",
    name: "Casual Sneakers",
    price: "$34.99",
    actual_price: "$45",
    star: 4.5,
    variant: ["white", "black", "red"],
    discount: "-40%",
  },
  {
    id: 5,
    image: "./trending5.jpg",
    name: "Leather Jacket",
    price: "$39.99",
    star: 5,
    variant: ["brown", "black"],
    discount: "-20%",
  },
  {
    id: 6,
    image: "./trending5.jpg",
    name: "Denim Shorts",
    price: "$44.99",
    actual_price: "$60",
    star: 4,
    discount: "-20%",
  },
  {
    id: 7,
    image: "./trending4.jpg",
    name: "Denim Shorts",
    price: "$44.99",
    actual_price: "$60",
    star: 4,
    discount: "-20%",
  },
  {
    id: 8,
    image: "./trending3.jpg",
    name: "Denim Shorts",
    price: "$44.99",
    actual_price: "$60",
    star: 4,
    discount: "-20%",
  },
  {
    id: 9,
    image: "./trending1.jpg",
    name: "Denim Shorts",
    price: "$44.99",
    actual_price: "$60",
    star: 4,
    discount: "-20%",
  },
  {
    id: 10,
    image: "./trending2.jpg",
    name: "Denim Shorts",
    price: "$44.99",
    actual_price: "$60",
    star: 4,
    discount: "-20%",
  },
];

export const newProducts = [
  {
    id: 1,
    image: "./newArraival.jpg",
    name: "Square Textured Striped",
    price: "$19.99",
    actual_price: "$120",
    star: 5,
    variant: ["red", "yellow"],
    discount: "-20%",
    preOrder: true,
  },
  {
    id: 2,
    image: "./newArraival2.jpg",
    name: "Rounded Neck T-Shirt",
    price: "$24.99",
    actual_price: "$720",
    star: 4.5,
    variant: ["blue", "green", "black"],
    discount: "-50%",
    preOrder: true,
  },
  {
    id: 3,
    image: "./newArraival3.jpg",
    name: "Slim Fit Jeans",
    price: "$29.99",
    star: 4,
    discount: "-20%",
  },
  {
    id: 4,
    image: "./newArraival4.jpg",
    name: "Casual Sneakers",
    price: "$34.99",
    actual_price: "$45",
    star: 4.5,
    variant: ["white", "black", "red"],
    discount: "-40%",
    preOrder: true,
  },
  {
    id: 5,
    image: "./newArraival5.jpg",
    name: "Leather Jacket",
    price: "$39.99",
    star: 5,
    variant: ["brown", "black"],
    discount: "-20%",
  },
  {
    id: 6,
    image: "./newArraival6.jpg",
    name: "Denim Shorts",
    price: "$44.99",
    actual_price: "$60",
    star: 4,
    preOrder: true,
  },
];

export const reviews = [
  {
    id: 1,
    image: "./card1.png",
    review:
      "A perfect product, it keeps you very warm without overheating. True to size, I couldn't be happier with the purchase... Thank you! 🤗",
    star: 5,
    name: "Algistino Lionel",
    status: "Verified Buyer",
  },
  {
    id: 2,
    image: "./card2.png",
    review:
      "Amazing quality! It fits perfectly and is very comfortable. Highly recommend to anyone looking for quality and style.",
    star: 4,
    name: "Jessica Miller",
    status: "Verified Buyer",
  },
  {
    id: 3,
    image: "./card3.png",
    review:
      "Good value for the price. The material feels premium and it's very stylish. Will definitely buy again.",
    star: 5,
    name: "Michael Brown",
    status: "Verified Buyer",
  },
  {
    id: 4,
    image: "./card1.png",
    review:
      "The product arrived on time and in excellent condition. It’s exactly as described. I’m very satisfied with my purchase.",
    star: 4,
    name: "Emily Johnson",
    status: "Verified Buyer",
  },
  {
    id: 5,
    image: "./card2.png",
    review:
      "Great product, very well made. The color and fit are perfect. I would recommend it to anyone looking for something similar.",
    star: 5,
    name: "Chris Evans",
    status: "Verified Buyer",
  },
  {
    id: 6,
    image: "./card3.png",
    review:
      "I love this product! It’s high-quality and fits exactly as expected. The customer service was also top-notch.",
    star: 4,
    name: "Sophia Lee",
    status: "Verified Buyer",
  },
];
